services:
   frontend:
    build:
            context: .
            dockerfile: dockerfile
    image: nguyenhaidev/wedding-page
    pull_policy: never
    ports:
      - "8100:80"
    restart: unless-stopped
